version: "3.8"

services:
  redis:
    image: redis:7.0
    container_name: gravit-redis-local
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data_local:/data

  postgres:
    image: postgres:15
    container_name: gravit-postgres-local
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - ./postgres_data_local:/var/lib/postgresql/data

  alloy:
    image: grafana/alloy:latest
    container_name: gravit-alloy
    ports:
      - "12345:12345"   # Alloy 상태/디버그 UI
    volumes:
      - ./logs:/var/log/spring                 # 스프링 로컬 로그 → Alloy가 읽을 경로
      - ./infra/config.alloy:/etc/alloy/config.alloy:ro
    environment:
      - ALLOY_ENV=local                        # 라벨로 들어감
    command: [ "run", "/etc/alloy/config.alloy" ]
    networks:
      - gravit-local

networks:
  gravit-local:
    external: true