-- 메인페이지 통합 테스트용: ID 1부터 시작하도록 IDENTITY 카운터 리셋
SET session_replication_role = replica;

TRUNCATE TABLE chapter CASCADE;
TRUNCATE TABLE unit CASCADE;
TRUNCATE TABLE lesson CASCADE;
TRUNCATE TABLE lesson_submission CASCADE;
TRUNCATE TABLE learning CASCADE;
TRUNCATE TABLE daily_learning_record CASCADE;
TRUNCATE TABLE mission CASCADE;

ALTER TABLE chapter ALTER COLUMN id RESTART WITH 1;
ALTER TABLE unit ALTER COLUMN id RESTART WITH 1;
ALTER TABLE lesson ALTER COLUMN id RESTART WITH 1;
ALTER TABLE lesson_submission ALTER COLUMN id RESTART WITH 1;
ALTER TABLE learning ALTER COLUMN id RESTART WITH 1;
ALTER TABLE daily_learning_record ALTER COLUMN id RESTART WITH 1;
ALTER TABLE mission ALTER COLUMN id RESTART WITH 1;

SET session_replication_role = DEFAULT;
