-- 사용자별 피드 상태를 관리하는 테이블 (fan-out on write)
CREATE TABLE user_feed (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT        NOT NULL,
    feed_id          BIGINT        NOT NULL,
    is_hidden        BOOLEAN       NOT NULL DEFAULT FALSE,
    congratulated_at TIMESTAMP(6),
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS ix_user_feed_user_id ON user_feed (user_id);
