-- 하루 축하 횟수 제한을 추적하기 위한 congratulation 테이블
CREATE TABLE congratulation (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    actor_id   BIGINT NOT NULL,
    feed_id    BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS ix_congratulation_user_actor_created ON congratulation (user_id, actor_id, created_at);
