-- FCM 디바이스 토큰을 저장하는 fcm_token 테이블
-- device_id: 클라이언트 디바이스 식별자. 기기 단위로 1행이며 전역 UNIQUE.
-- token: 해당 기기의 현재 FCM 등록 토큰. 주기적으로 갱신된다.
-- 한 유저가 여러 기기를 가지면 device_id가 다른 여러 행을 갖는다(멀티 디바이스).
CREATE TABLE fcm_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    device_id  VARCHAR(255) NOT NULL,
    token      VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uq_fcm_token_device_id UNIQUE (device_id),
    CONSTRAINT fk_fcm_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 발송 시 유저별 토큰 조회를 위한 인덱스
CREATE INDEX IF NOT EXISTS ix_fcm_token_user_id ON fcm_token (user_id);
