-- admin 감사 로그 테이블. (조회 API 는 범위 밖 — 기록 전용)
-- action 5종: user status/role 변경, notice DELETE/status 전이, staging promote.
CREATE TABLE audit_log
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    admin_id     BIGINT       NOT NULL,
    action       VARCHAR(40)  NOT NULL CHECK (action IN
                                              ('USER_STATUS_CHANGE', 'USER_ROLE_CHANGE',
                                               'NOTICE_DELETE', 'NOTICE_STATUS_CHANGE', 'STAGING_PROMOTE')),
    target_id    VARCHAR(64)  NOT NULL,
    before_value VARCHAR(255),
    after_value  VARCHAR(255),
    created_at   TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_audit_log_admin ON audit_log (admin_id);
