-- V5__add_daily_learning_record.sql

-- 일자별 학습 이력 (GitHub 잔디 UI 및 주간 학습 기록용)
-- 기존 learning 테이블(누적 상태)과 책임 분리
CREATE TABLE IF NOT EXISTS daily_learning_record
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT  NOT NULL,
    solved_date         DATE    NOT NULL,
    solved_lesson_count INTEGER NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_daily_learning_record_user_date
        UNIQUE (user_id, solved_date)
);

-- 사용자별 기간 조회(주간 학습 기록 등) 최적화용 인덱스
CREATE INDEX IF NOT EXISTS ix_daily_learning_record_user_date
    ON daily_learning_record (user_id, solved_date);
