-- Social Feed Table
CREATE TABLE social_feed
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    actor_id    BIGINT       NOT NULL,
    event_type  VARCHAR(255) NOT NULL CHECK (event_type IN ('PLANET_COMPLETE', 'STREAK_DAYS', 'TIER_PROMOTION', 'LEVEL_UP')),
    event_value VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- Indexes for feed query performance
CREATE INDEX IF NOT EXISTS ix_social_feed_actor_id ON social_feed (actor_id);
CREATE INDEX IF NOT EXISTS ix_social_feed_created_at ON social_feed (created_at DESC);
